### ISSUE TITLE
after update it's not working

### ISSUE THREAD

**Issue by unecc** [Andre0512/hon#117]
Hi Andre, i've just update hass but hon does not work anymore.
Can you update your fantastic software?

**Comment by Andre0512** [comment]
Hi unecc, which version do you use? There was an dependency error for home assistant 2023.10.x, this was fixed with [`v0.10.0`](https://github.com/Andre0512/hon/releases/tag/v0.10.0).

**Comment by itnassol** [comment]
Same here using v0.10.0 command not sending, have re-installed but still not responding.

**Comment by Andre0512** [comment]
Do you see an error message in the logs?

**Comment by itnassol** [comment]
Yes there wee a couple, they were.

This error originated from a custom integration.

Logger: pyhon.commands
Source: custom_components/hon/switch.py:472
Integration: Haier hOn (documentation, issues)
First occurred: 11:29:28 (17 occurrences)
Last logged: 11:56:55

False

and there was

This error originated from a custom integration.

Logger: pyhon.connection.api
Source: custom_components/hon/switch.py:472
Integration: Haier hOn (documentation, issues)
First occurred: 11:29:28 (34 occurrences)
Last logged: 11:56:55

https://api-iot.he.services/commands/v1/send - Payload: {'ancillaryParameters': {'energyLabel': '5', 'liquidDetergentDose': '1', 'programFamily': '[guided|voice]', 'programType': 'W+D', 'remoteActionable': '1', 'remoteVisible': '0', 'suggestedLoadW': '2', 'tempContribution': '0'}, 'applianceOptions': {'opt1': 'prewash', 'opt2': 'hygiene', 'opt3': 'anticrease', 'opt4': 'goodNight', 'opt5': 'extraRinse1', 'opt6': 'extraRinse2', 'opt7': 'extraRinse3', 'opt8': 'acquaplus'}, 'applianceType': 'WM', 'attributes': {'channel': 'mobileApp', 'energyLabel': '0', 'origin': 'standardProgram'}, 'commandName': 'startProgram', 'device': {'appVersion': '2.1.2', 'deviceModel': 'exynos9820', 'mobileId': 'dacd280d1635e79d', 'mobileOs': 'android', 'osVersion': 31}, 'macAddress': '10-97-bd-73-28-58', 'parameters': {'acquaplus': '0', 'anticrease': '0', 'checkUpStatus': '0', 'delayTime': '0', 'dirtyLevel': '1', 'extraRinse1': '0', 'extraRinse2': '0', 'extraRinse3': '0', 'goodNight': '0', 'hygiene': '0', 'lang': '1', 'onOffStatus': '1', 'prCode': '9', 'prPosition': '13', 'prStr': '', 'prewash': '0', 'spinSpeed': '800', 'steamLevel': '0', 'temp': '30'}, 'timestamp': '2023-10-05T10:55:21.840Z', 'transactionId': '10-97-bd-73-28-58_2023-10-05T10:55:21.840Z'}
https://api-iot.he.services/commands/v1/send - Payload: {'ancillaryParameters': {'energyLabel': '5', 'liquidDetergentDose': '1', 'programFamily': '[guided|voice]', 'programType': 'W+D', 'remoteActionable': '1', 'remoteVisible': '0', 'suggestedLoadW': '2', 'tempContribution': '0'}, 'applianceOptions': {'opt1': 'prewash', 'opt2': 'hygiene', 'opt3': 'anticrease', 'opt4': 'goodNight', 'opt5': 'extraRinse1', 'opt6': 'extraRinse2', 'opt7': 'extraRinse3', 'opt8': 'acquaplus'}, 'applianceType': 'WM', 'attributes': {'channel': 'mobileApp', 'energyLabel': '0', 'origin': 'standardProgram'}, 'commandName': 'startProgram', 'device': {'appVersion': '2.1.2', 'deviceModel': 'exynos9820', 'mobileId': 'dacd280d1635e79d', 'mobileOs': 'android', 'osVersion': 31}, 'macAddress': '10-97-bd-73-28-58', 'parameters': {'acquaplus': '0', 'anticrease': '0', 'checkUpStatus': '0', 'delayTime': '0', 'dirtyLevel': '1', 'extraRinse1': '0', 'extraRinse2': '0', 'extraRinse3': '0', 'goodNight': '0', 'hygiene': '0', 'lang': '1', 'onOffStatus': '1', 'prCode': '9', 'prPosition': '13', 'prStr': '', 'prewash': '0', 'spinSpeed': '800', 'steamLevel': '0', 'temp': '30'}, 'timestamp': '2023-10-05T10:55:50.249Z', 'transactionId': '10-97-bd-73-28-58_2023-10-05T10:55:50.249Z'}
{"payload":{"resultCode":"1","errorCode":"1000","errorDescription":"Invalid parameter: parValue"},"authInfo":{}}
https://api-iot.he.services/commands/v1/send - Payload: {'ancillaryParameters': {'energyLabel': '5', 'liquidDetergentDose': '1', 'programFamily': '[guided|voice]', 'programType': 'W+D', 'remoteActionable': '1', 'remoteVisible': '0', 'suggestedLoadW': '2', 'tempContribution': '0'}, 'applianceOptions': {'opt1': 'prewash', 'opt2': 'hygiene', 'opt3': 'anticrease', 'opt4': 'goodNight', 'opt5': 'extraRinse1', 'opt6': 'extraRinse2', 'opt7': 'extraRinse3', 'opt8': 'acquaplus'}, 'applianceType': 'WM', 'attributes': {'channel': 'mobileApp', 'energyLabel': '0', 'origin': 'standardProgram'}, 'commandName': 'startProgram', 'device': {'appVersion': '2.1.2', 'deviceModel': 'exynos9820', 'mobileId': 'dacd280d1635e79d', 'mobileOs': 'android', 'osVersion': 31}, 'macAddress': '10-97-bd-73-28-58', 'parameters': {'acquaplus': '0', 'anticrease': '0', 'checkUpStatus': '0', 'delayTime': '0', 'dirtyLevel': '1', 'extraRinse1': '0', 'extraRinse2': '0', 'extraRinse3': '0', 'goodNight': '0', 'hygiene': '0', 'lang': '1', 'onOffStatus': '1', 'prCode': '9', 'prPosition': '13', 'prStr': '', 'prewash': '0', 'spinSpeed': '800', 'steamLevel': '0', 'temp': '30'}, 'timestamp': '2023-10-05T10:56:03.220Z', 'transactionId': '10-97-bd-73-28-58_2023-10-05T10:56:03.220Z'}
https://api-iot.he.services/commands/v1/send - Payload: {'ancillaryParameters': {'energyLabel': '5', 'liquidDetergentDose': '1', 'programFamily': '[guided|voice]', 'programType': 'W+D', 'remoteActionable': '1', 'remoteVisible': '0', 'suggestedLoadW': '2', 'tempContribution': '0'}, 'applianceOptions': {'opt1': 'prewash', 'opt2': 'hygiene', 'opt3': 'anticrease', 'opt4': 'goodNight', 'opt5': 'extraRinse1', 'opt6': 'extraRinse2', 'opt7': 'extraRinse3', 'opt8': 'acquaplus'}, 'applianceType': 'WM', 'attributes': {'channel': 'mobileApp', 'energyLabel': '0', 'origin': 'standardProgram'}, 'commandName': 'startProgram', 'device': {'appVersion': '2.1.2', 'deviceModel': 'exynos9820', 'mobileId': 'dacd280d1635e79d', 'mobileOs': 'android', 'osVersion': 31}, 'macAddress': '10-97-bd-73-28-58', 'parameters': {'acquaplus': '0', 'anticrease': '0', 'checkUpStatus': '0', 'delayTime': '0', 'dirtyLevel': '1', 'extraRinse1': '0', 'extraRinse2': '0', 'extraRinse3': '0', 'goodNight': '0', 'hygiene': '0', 'lang': '1', 'onOffStatus': '1', 'prCode': '9', 'prPosition': '13', 'prStr': '', 'prewash': '0', 'spinSpeed': '800', 'steamLevel': '0', 'temp': '30'}, 'timestamp': '2023-10-05T10:56:54.677Z', 'transactionId': '10-97-bd-73-28-58_2023-10-05T10:56:54.677Z'}

**Comment by Andre0512** [comment]
Okay that is another bug, it looks like some parameter is missing or some parameter has a wrong value when you trying to start your machine. Can you share your data archive? Then I can try to debug this.

> **Data Archive**
> For further analysis, please add your appliance data archive here (if available)
> Navigate to `Settings` -> `Device & Services` -> `Haier hOn` -> _your device_ and press the _Create Data Archive_ button. 
> Then open notifications to download the data zip archive.
> To attach the file:
> * GitHub Web: Use the "Attach files by dragging & dropping, selecting or pasting them." function
> * GitHub Mobile: Upload the zip archive as image

**Comment by itnassol** [comment]
[wm_154.zip](https://github.com/Andre0512/hon/files/12821088/wm_154.zip)
Hope this correct, thank you so much for your help.

**Comment by unecc** [comment]
Thanks Andre, new version works perfectly

**Comment by Andre0512** [comment]
I think it could be the empty `prStr` that causes the issue, please try [`v0.10.1-beta.1`](https://github.com/Andre0512/hon/releases/tag/v0.10.1-beta.1)

**Comment by Andre0512** [comment]
Sounds good, thanks for testing!

This is not necessary, but I have created one now :smiley: 

<a href="https://www.buymeacoffee.com/andre0512" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-blue.png" alt="Buy Me A Coffee"></a>
