### ISSUE TITLE
Aie Conditioner Fan mode cannot be set to auto

### ISSUE THREAD

**Issue by andremain** [Andre0512/hon#84]
When i select auto fan mode it cannot call service. Available values 1,2,3,5

**Comment by Andre0512** [comment]
Hi, can you please share your device data as archive? (Install the latest beta)

> **Data Archive**
> For further analysis, please add your appliance data archive here.
> Navigate to `Settings` -> `Device & Services` -> `Haier hOn` -> _your device_ and press the > _Create Data Archive_ button. 
> Then open notifications to download the data zip archive.
> To attach the file:
> * GitHub Web: Use the "Attach files by dragging & dropping, selecting or pasting them."  function
> * GitHub Mobile: Upload the zip archive as image

**Comment by andremain** [comment]
Sorry for the wait.

Here is the code:


``` data: additional_data: appliance: SK_Secondary: AC#selfClean56#2022-10-24 applianceId: xx-xx-xx-xx-xx-xx#2022-08-25T13:38:15Z applianceModelId: 342 applianceStatus: 1 applianceTypeId: 11 applianceTypeName: AC attributes: acuVersion: 06.26.00 chipset: 1 dictionaryId: 183 eppParserSet: 1 fwLabel: iotfw_epp lang: it-IT uiVersion: 06.26.00 brand: haier code: AABL80E0000 connectivity: wifi|ble eepromId: 41 eepromName: no_eeprom enrollmentDate: 2022-08-25T13:38:15.968Z firstEnrollment: True firstEnrollmentTBC: True fwVersion: 5.12.0 id: 342 lastUpdate: 2022-08-25T13:40:54Z macAddress: xx-xx-xx-xx-xx-xx modelName: AS35TAMHRA-C nickName: Bedroom 3 AC purchaseDate: 2022-08-24T21:00:00.000Z sections: chatbot: True double_pairing_hidden: True epp_enabled: False series: tundra topics: publish: subscribe: - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update unitConfiguration: 1to1 attributes: activity: activityExecutionStarted: 2023-06-30 20:58:05 activityStarted: 2023-06-30T20:58:05Z applianceTypeName: AC attributes: 10degreeHeatingStatus: 0 acType: 0 airQuality: 0 appVersion: 2.0.10 ch2oCleaningStatus: 0 ch2oValueIndoor: 0 channel: mobileApp cleaningTimeStatus: 0 co2ValueIndoor: 0 compressorCurrent: 51.10 compressorFrequency: 0 compressorStatus: 0 defrostStatus: 0 deviceModel: exynos9820 echoStatus: 0 ecoMode: 0 electricHeatingStatus: 0 electricHeatingStatusIndoor: 0 energySavePeriod: 15 energySavingStatus: 0 errAckFlag: 0 expansionValveOpenDegree: 88 fanStatusIndoor: 0 fanStatusOutdoor: 2 filterChangeStatusCloud: 0 fourWayValveStatus: 2 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 humanSensingStatus: 0 humidificationStatus: 0 humidityIndoor: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 1 machineModeHK: 0 mobileOs: android muteStatus: 0 operationSource: 3 origin: standardProgram osVersion: 31 pm2p5CleaningStatus: 0 pm2p5LevelIndoor: 0 pm2p5ValueIndoor: 0 pm2p5ValueOutdoor: 0 pmvStatus: 0 power: 0 principalUserId: 0016800000ETo7bAAD programFamily: [standard] rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 sensingResult: 0 silentSleepStatus: 0 specialMode: 0 tempAirOutdoor: 47 tempCoilerIndoor: 27.00 tempCoilerOutdoor: 24 tempDefrostOutdoor: -64 tempInAirOutdoor: -64 tempIndoor: 29.50 tempOutdoor: 26.00 tempSel: 22 tempUnit: 0 vocValueIndoor: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 5 category: CYCLE macAddress: xx-xx-xx-xx-xx-xx resultCode: 0 ttl: 1695934685 commandHistory: command: ancillaryParameters: ecoMode: 0 programFamily: [standard] remoteActionable: 1 remoteVisible: 1 applianceOptions: applianceType: AC attributes: channel: mobileApp energyLabel: 0 origin: standardProgram commandName: startProgram device: appVersion: 2.0.10 deviceModel: exynos9820 mobileId: 5251f0304a1a7e85 mobileOs: android osVersion: 31 macAddress: xx-xx-xx-xx-xx-xx parameters: 10degreeHeatingStatus: 0 ch2oCleaningStatus: 0 cleaningTimeStatus: 0 echoStatus: 0 electricHeatingStatus: 0 energySavePeriod: 15 energySavingStatus: 0 filterChangeStatusCloud: 0 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 humanSensingStatus: 0 humidificationStatus: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 1 muteStatus: 0 onOffStatus: 1 operationName: grSetDAC pm2p5CleaningStatus: 0 pmvStatus: 0 rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 silentSleepStatus: 0 specialMode: 0 tempSel: 22 tempUnit: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 5 timestamp: 2023-06-30T20:58:02.722Z transactionId: xx-xx-xx-xx-xx-xx_2023-06-30T20:58:02.722Z timestampAccepted: 2023-06-30T21:27:38.0Z timestampExecuted: 2023-06-30T21:27:38.8Z lastConnEvent: category: CONNECTED instantTime: 2023-06-29T08:31:57Z macAddress: xx-xx-xx-xx-xx-xx timestampEvent: 1688027517594 parameters: 10degreeHeatingStatus: 0 acType: 0 airQuality: 0 ch2oCleaningStatus: 0 ch2oValueIndoor: 0 co2ValueIndoor: 0 compressorCurrent: 51.10 compressorFrequency: 48 compressorStatus: 1 debugEnabled: 0 defrostStatus: 0 echoStatus: 0 electricHeatingStatus: 0 electricHeatingStatusIndoor: 0 energySavePeriod: 15 energySavingStatus: 0 errAckFlag: 0 errCode: 0 errors: 00 expansionValveOpenDegree: 88 fanStatusIndoor: 1 fanStatusOutdoor: 2 filterChangeStatusLocal: 0 fourWayValveStatus: 2 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 highTransRate: 1 humanSensingStatus: 0 humidificationStatus: 0 humidityIndoor: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 1 machineModeHK: 0 muteStatus: 0 onOffStatus: 1 operationSource: 3 pm2p5CleaningStatus: 0 pm2p5LevelIndoor: 0 pm2p5ValueIndoor: 0 pm2p5ValueOutdoor: 0 pmvStatus: 0 power: 0 rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 sensingResult: 0 silentSleepStatus: 0 specialMode: 0 statusSyncRate: 1440 stdTransRate: 3600 tempAirOutdoor: 48 tempCoilerIndoor: 10.00 tempCoilerOutdoor: 29 tempDefrostOutdoor: -64 tempInAirOutdoor: -64 tempIndoor: 25.50 tempOutdoor: 26.00 tempSel: 24.00 tempUnit: 0 totalElectricityUsed: 0 totalWorkTime: 0 transMode: 0 vocValueIndoor: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 1 resultCode: 0 settings: ancillaryParameters: programRules: {'tempSel': {'ecoMode': {'1': {'machMode': {'1': {'typology': 'fixed', 'fixedValue': '26'}, '4': {'typology': 'fixed', 'fixedValue': '20'}}}}}, 'windSpeed': {'ecoMode': {'1': {'machMode': {'1|4': {'typology': 'enum', 'defaultValue': '1', 'enumValues': '1|2|3|5'}}}}}, 'windDirectionVertical': {'ecoMode': {'1': {'machMode': {'1|4': {'typology': 'fixed', 'fixedValue': '3'}}}}}} custom: category: setParameters parameters: 10degreeHeatingStatus: 0 ch2oCleaningStatus: 0 cleaningTimeStatus: 0 echoStatus: 0 electricHeatingStatus: 0 energySavePeriod: 15 energySavingStatus: 0 filterChangeStatusCloud: 0 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 humanSensingStatus: 0 humidificationStatus: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 1 muteStatus: 0 onOffStatus: 1 operationName: grSetDAC pm2p5CleaningStatus: 0 pmvStatus: 0 rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 silentSleepStatus: 0 specialMode: 0 tempSel: 24 tempUnit: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 1 startProgram: ancillaryParameters: ecoMode: 0 programFamily: [standard] programRules: {'tempSel': {'ecoMode': {'1': {'machMode': {'1': {'typology': 'fixed', 'fixedValue': '26'}, '4': {'typology': 'fixed', 'fixedValue': '20'}}}}}, 'windSpeed': {'ecoMode': {'1': {'machMode': {'1|4': {'typology': 'enum', 'defaultValue': '1', 'enumValues': '1|2|3|5'}}}}}, 'windDirectionVertical': {'ecoMode': {'1': {'machMode': {'1|4': {'typology': 'fixed', 'fixedValue': '3'}}}}}} remoteActionable: 1 remoteVisible: 1 custom: program: iot_cool parameters: 10degreeHeatingStatus: 0 ch2oCleaningStatus: 0 cleaningTimeStatus: 0 echoStatus: 0 electricHeatingStatus: 0 energySavePeriod: 15 energySavingStatus: 0 filterChangeStatusCloud: 0 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 humanSensingStatus: 0 humidificationStatus: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 1 muteStatus: 0 onOffStatus: 1 operationName: grSetDAC pm2p5CleaningStatus: 0 pmvStatus: 0 rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 silentSleepStatus: 0 specialMode: 0 tempSel: 22 tempUnit: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 5 statistics: mostUsedPrograms: - count: 260 prCode: None programName: PROGRAMS.AC.HOME_ASSISTANT - count: 3 prCode: None programName: PROGRAMS.AC.IOT_COOL mostUsedRecipes: programsCounter: 0 stopProgram: parameters: 10degreeHeatingStatus: 0 ch2oCleaningStatus: 0 cleaningTimeStatus: 0 echoStatus: 0 electricHeatingStatus: 0 energySavePeriod: 15 energySavingStatus: 0 filterChangeStatusCloud: 0 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 humanSensingStatus: 0 humidificationStatus: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 0 muteStatus: 0 onOffStatus: 0 operationName: grSetDAC pm2p5CleaningStatus: 0 pmvStatus: 0 rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 silentSleepStatus: 0 specialMode: 0 tempSel: 22 tempUnit: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 5 commands: settings: 10degreeHeatingStatus: max: 0 min: 0 step: 1 category: - setConfig - setParameters echoStatus: max: 1 min: 0 step: 1 machMode: - 0 - 1 - 2 - 4 - 6 muteStatus: max: 1 min: 0 step: 1 rapidMode: max: 1 min: 0 step: 1 screenDisplayStatus: max: 1 min: 0 step: 1 selfCleaningStatus: max: 0 min: 0 step: 1 silentSleepStatus: max: 1 min: 0 step: 1 tempSel: max: 30 min: 16 step: 1 windDirectionVertical: - 2 - 4 - 5 - 6 - 7 - 8 windSpeed: - 1 - 2 - 3 - 5 startProgram: 10degreeHeatingStatus: max: 1 min: 0 step: 1 echoStatus: max: 1 min: 0 step: 1 ecoMode: max: 1 min: 0 step: 1 machMode: - 0 - 1 - 2 - 4 - 6 muteStatus: max: 1 min: 0 step: 1 program: - iot_10_heating - iot_auto - iot_cool - iot_dry - iot_fan - iot_heat - iot_self_clean - iot_simple_start programFamily: - maintenance - health - maintenance_health rapidMode: max: 1 min: 0 step: 1 remoteActionable: max: 1 min: 0 step: 1 remoteVisible: max: 1 min: 0 step: 1 screenDisplayStatus: max: 1 min: 0 step: 1 selfCleaningStatus: max: 1 min: 0 step: 1 silentSleepStatus: max: 1 min: 0 step: 1 tempSel: max: 30 min: 16 step: 1 windDirectionVertical: - 2 - 4 - 5 - 6 - 7 - 8 windSpeed: - 1 - 2 - 3 - 5 stopProgram: 10degreeHeatingStatus: max: 1 min: 0 step: 1 echoStatus: max: 1 min: 0 step: 1 machMode: - 0 - 1 - 2 - 4 - 6 muteStatus: max: 1 min: 0 step: 1 rapidMode: max: 1 min: 0 step: 1 screenDisplayStatus: max: 1 min: 0 step: 1 selfCleaningStatus: max: 1 min: 0 step: 1 silentSleepStatus: max: 1 min: 0 step: 1 tempSel: max: 30 min: 16 step: 1 windDirectionVertical: - 2 - 4 - 5 - 6 - 7 - 8 windSpeed: - 1 - 2 - 3 - 5 rules: startProgram: ecoMode: 1: tempSel: None windDirectionVertical: None windSpeed: None pyhOnVersion: 0.12.4 ```

**Comment by Andre0512** [comment]
Hey no problem! Thanks, I have added a new feature in the latest beta to download a zip archive with all available data. Can you please attach that as well? (like describe in the last message). Then I can see the full configuration of the auto-fan mode and it's much easier to find the problem :slightly_smiling_face:

**Comment by andremain** [comment]
Sorry for the wait.

Here is the code:


``` data: additional_data: appliance: SK_Secondary: AC#selfClean56#2022-10-24 applianceId: xx-xx-xx-xx-xx-xx#2022-08-25T13:38:15Z applianceModelId: 342 applianceStatus: 1 applianceTypeId: 11 applianceTypeName: AC attributes: acuVersion: 06.26.00 chipset: 1 dictionaryId: 183 eppParserSet: 1 fwLabel: iotfw_epp lang: it-IT uiVersion: 06.26.00 brand: haier code: AABL80E0000 connectivity: wifi|ble eepromId: 41 eepromName: no_eeprom enrollmentDate: 2022-08-25T13:38:15.968Z firstEnrollment: True firstEnrollmentTBC: True fwVersion: 5.12.0 id: 342 lastUpdate: 2022-08-25T13:40:54Z macAddress: xx-xx-xx-xx-xx-xx modelName: AS35TAMHRA-C nickName: Bedroom 3 AC purchaseDate: 2022-08-24T21:00:00.000Z sections: chatbot: True double_pairing_hidden: True epp_enabled: False series: tundra topics: publish: subscribe: - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update unitConfiguration: 1to1 attributes: activity: activityExecutionStarted: 2023-06-30 20:58:05 activityStarted: 2023-06-30T20:58:05Z applianceTypeName: AC attributes: 10degreeHeatingStatus: 0 acType: 0 airQuality: 0 appVersion: 2.0.10 ch2oCleaningStatus: 0 ch2oValueIndoor: 0 channel: mobileApp cleaningTimeStatus: 0 co2ValueIndoor: 0 compressorCurrent: 51.10 compressorFrequency: 0 compressorStatus: 0 defrostStatus: 0 deviceModel: exynos9820 echoStatus: 0 ecoMode: 0 electricHeatingStatus: 0 electricHeatingStatusIndoor: 0 energySavePeriod: 15 energySavingStatus: 0 errAckFlag: 0 expansionValveOpenDegree: 88 fanStatusIndoor: 0 fanStatusOutdoor: 2 filterChangeStatusCloud: 0 fourWayValveStatus: 2 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 humanSensingStatus: 0 humidificationStatus: 0 humidityIndoor: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 1 machineModeHK: 0 mobileOs: android muteStatus: 0 operationSource: 3 origin: standardProgram osVersion: 31 pm2p5CleaningStatus: 0 pm2p5LevelIndoor: 0 pm2p5ValueIndoor: 0 pm2p5ValueOutdoor: 0 pmvStatus: 0 power: 0 principalUserId: 0016800000ETo7bAAD programFamily: [standard] rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 sensingResult: 0 silentSleepStatus: 0 specialMode: 0 tempAirOutdoor: 47 tempCoilerIndoor: 27.00 tempCoilerOutdoor: 24 tempDefrostOutdoor: -64 tempInAirOutdoor: -64 tempIndoor: 29.50 tempOutdoor: 26.00 tempSel: 22 tempUnit: 0 vocValueIndoor: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 5 category: CYCLE macAddress: xx-xx-xx-xx-xx-xx resultCode: 0 ttl: 1695934685 commandHistory: command: ancillaryParameters: ecoMode: 0 programFamily: [standard] remoteActionable: 1 remoteVisible: 1 applianceOptions: applianceType: AC attributes: channel: mobileApp energyLabel: 0 origin: standardProgram commandName: startProgram device: appVersion: 2.0.10 deviceModel: exynos9820 mobileId: 5251f0304a1a7e85 mobileOs: android osVersion: 31 macAddress: xx-xx-xx-xx-xx-xx parameters: 10degreeHeatingStatus: 0 ch2oCleaningStatus: 0 cleaningTimeStatus: 0 echoStatus: 0 electricHeatingStatus: 0 energySavePeriod: 15 energySavingStatus: 0 filterChangeStatusCloud: 0 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 humanSensingStatus: 0 humidificationStatus: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 1 muteStatus: 0 onOffStatus: 1 operationName: grSetDAC pm2p5CleaningStatus: 0 pmvStatus: 0 rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 silentSleepStatus: 0 specialMode: 0 tempSel: 22 tempUnit: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 5 timestamp: 2023-06-30T20:58:02.722Z transactionId: xx-xx-xx-xx-xx-xx_2023-06-30T20:58:02.722Z timestampAccepted: 2023-06-30T21:27:38.0Z timestampExecuted: 2023-06-30T21:27:38.8Z lastConnEvent: category: CONNECTED instantTime: 2023-06-29T08:31:57Z macAddress: xx-xx-xx-xx-xx-xx timestampEvent: 1688027517594 parameters: 10degreeHeatingStatus: 0 acType: 0 airQuality: 0 ch2oCleaningStatus: 0 ch2oValueIndoor: 0 co2ValueIndoor: 0 compressorCurrent: 51.10 compressorFrequency: 48 compressorStatus: 1 debugEnabled: 0 defrostStatus: 0 echoStatus: 0 electricHeatingStatus: 0 electricHeatingStatusIndoor: 0 energySavePeriod: 15 energySavingStatus: 0 errAckFlag: 0 errCode: 0 errors: 00 expansionValveOpenDegree: 88 fanStatusIndoor: 1 fanStatusOutdoor: 2 filterChangeStatusLocal: 0 fourWayValveStatus: 2 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 highTransRate: 1 humanSensingStatus: 0 humidificationStatus: 0 humidityIndoor: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 1 machineModeHK: 0 muteStatus: 0 onOffStatus: 1 operationSource: 3 pm2p5CleaningStatus: 0 pm2p5LevelIndoor: 0 pm2p5ValueIndoor: 0 pm2p5ValueOutdoor: 0 pmvStatus: 0 power: 0 rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 sensingResult: 0 silentSleepStatus: 0 specialMode: 0 statusSyncRate: 1440 stdTransRate: 3600 tempAirOutdoor: 48 tempCoilerIndoor: 10.00 tempCoilerOutdoor: 29 tempDefrostOutdoor: -64 tempInAirOutdoor: -64 tempIndoor: 25.50 tempOutdoor: 26.00 tempSel: 24.00 tempUnit: 0 totalElectricityUsed: 0 totalWorkTime: 0 transMode: 0 vocValueIndoor: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 1 resultCode: 0 settings: ancillaryParameters: programRules: {'tempSel': {'ecoMode': {'1': {'machMode': {'1': {'typology': 'fixed', 'fixedValue': '26'}, '4': {'typology': 'fixed', 'fixedValue': '20'}}}}}, 'windSpeed': {'ecoMode': {'1': {'machMode': {'1|4': {'typology': 'enum', 'defaultValue': '1', 'enumValues': '1|2|3|5'}}}}}, 'windDirectionVertical': {'ecoMode': {'1': {'machMode': {'1|4': {'typology': 'fixed', 'fixedValue': '3'}}}}}} custom: category: setParameters parameters: 10degreeHeatingStatus: 0 ch2oCleaningStatus: 0 cleaningTimeStatus: 0 echoStatus: 0 electricHeatingStatus: 0 energySavePeriod: 15 energySavingStatus: 0 filterChangeStatusCloud: 0 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 humanSensingStatus: 0 humidificationStatus: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 1 muteStatus: 0 onOffStatus: 1 operationName: grSetDAC pm2p5CleaningStatus: 0 pmvStatus: 0 rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 silentSleepStatus: 0 specialMode: 0 tempSel: 24 tempUnit: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 1 startProgram: ancillaryParameters: ecoMode: 0 programFamily: [standard] programRules: {'tempSel': {'ecoMode': {'1': {'machMode': {'1': {'typology': 'fixed', 'fixedValue': '26'}, '4': {'typology': 'fixed', 'fixedValue': '20'}}}}}, 'windSpeed': {'ecoMode': {'1': {'machMode': {'1|4': {'typology': 'enum', 'defaultValue': '1', 'enumValues': '1|2|3|5'}}}}}, 'windDirectionVertical': {'ecoMode': {'1': {'machMode': {'1|4': {'typology': 'fixed', 'fixedValue': '3'}}}}}} remoteActionable: 1 remoteVisible: 1 custom: program: iot_cool parameters: 10degreeHeatingStatus: 0 ch2oCleaningStatus: 0 cleaningTimeStatus: 0 echoStatus: 0 electricHeatingStatus: 0 energySavePeriod: 15 energySavingStatus: 0 filterChangeStatusCloud: 0 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 humanSensingStatus: 0 humidificationStatus: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 1 muteStatus: 0 onOffStatus: 1 operationName: grSetDAC pm2p5CleaningStatus: 0 pmvStatus: 0 rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 silentSleepStatus: 0 specialMode: 0 tempSel: 22 tempUnit: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 5 statistics: mostUsedPrograms: - count: 260 prCode: None programName: PROGRAMS.AC.HOME_ASSISTANT - count: 3 prCode: None programName: PROGRAMS.AC.IOT_COOL mostUsedRecipes: programsCounter: 0 stopProgram: parameters: 10degreeHeatingStatus: 0 ch2oCleaningStatus: 0 cleaningTimeStatus: 0 echoStatus: 0 electricHeatingStatus: 0 energySavePeriod: 15 energySavingStatus: 0 filterChangeStatusCloud: 0 freshAirStatus: 0 halfDegreeSettingStatus: 0 healthMode: 0 heatAccumulationStatus: 0 humanSensingStatus: 0 humidificationStatus: 0 humiditySel: 30 intelligenceStatus: 0 lightStatus: 0 lockStatus: 0 machMode: 0 muteStatus: 0 onOffStatus: 0 operationName: grSetDAC pm2p5CleaningStatus: 0 pmvStatus: 0 rapidMode: 0 screenDisplayStatus: 1 selfCleaning56Status: 0 selfCleaningStatus: 0 silentSleepStatus: 0 specialMode: 0 tempSel: 22 tempUnit: 0 voiceSignStatus: 0 voiceStatus: 0 windDirectionHorizontal: 0 windDirectionVertical: 5 windSensingStatus: 0 windSpeed: 5 commands: settings: 10degreeHeatingStatus: max: 0 min: 0 step: 1 category: - setConfig - setParameters echoStatus: max: 1 min: 0 step: 1 machMode: - 0 - 1 - 2 - 4 - 6 muteStatus: max: 1 min: 0 step: 1 rapidMode: max: 1 min: 0 step: 1 screenDisplayStatus: max: 1 min: 0 step: 1 selfCleaningStatus: max: 0 min: 0 step: 1 silentSleepStatus: max: 1 min: 0 step: 1 tempSel: max: 30 min: 16 step: 1 windDirectionVertical: - 2 - 4 - 5 - 6 - 7 - 8 windSpeed: - 1 - 2 - 3 - 5 startProgram: 10degreeHeatingStatus: max: 1 min: 0 step: 1 echoStatus: max: 1 min: 0 step: 1 ecoMode: max: 1 min: 0 step: 1 machMode: - 0 - 1 - 2 - 4 - 6 muteStatus: max: 1 min: 0 step: 1 program: - iot_10_heating - iot_auto - iot_cool - iot_dry - iot_fan - iot_heat - iot_self_clean - iot_simple_start programFamily: - maintenance - health - maintenance_health rapidMode: max: 1 min: 0 step: 1 remoteActionable: max: 1 min: 0 step: 1 remoteVisible: max: 1 min: 0 step: 1 screenDisplayStatus: max: 1 min: 0 step: 1 selfCleaningStatus: max: 1 min: 0 step: 1 silentSleepStatus: max: 1 min: 0 step: 1 tempSel: max: 30 min: 16 step: 1 windDirectionVertical: - 2 - 4 - 5 - 6 - 7 - 8 windSpeed: - 1 - 2 - 3 - 5 stopProgram: 10degreeHeatingStatus: max: 1 min: 0 step: 1 echoStatus: max: 1 min: 0 step: 1 machMode: - 0 - 1 - 2 - 4 - 6 muteStatus: max: 1 min: 0 step: 1 rapidMode: max: 1 min: 0 step: 1 screenDisplayStatus: max: 1 min: 0 step: 1 selfCleaningStatus: max: 1 min: 0 step: 1 silentSleepStatus: max: 1 min: 0 step: 1 tempSel: max: 30 min: 16 step: 1 windDirectionVertical: - 2 - 4 - 5 - 6 - 7 - 8 windSpeed: - 1 - 2 - 3 - 5 rules: startProgram: ecoMode: 1: tempSel: None windDirectionVertical: None windSpeed: None pyhOnVersion: 0.12.4 ``````
![ac_342.zip](https://github.com/Andre0512/hon/files/11925260/ac_342.zip)


```

**Comment by andremain** [comment]
Did however using thr latest beta none of the fan modes work

**Comment by Andre0512** [comment]
Hi, please test the last beta version, should be working now :slightly_smiling_face:

**Comment by andremain** [comment]
> Hi, please test the last beta version, should be working now :slightly_smiling_face: 

Thanks, the other modes are n9w working but auto still isn't

**Comment by Andre0512** [comment]
Hey, is the error still occurring? I have tried to recreate the error but have no success yet :thinking:

**Comment by andremain** [comment]
> Hey, is the error still occurring? I have tried to recreate the error but have no success yet :thinking: 

Yeah, i downloaded the newest beta but i get the same error.
Failed to call service climate/set fan mode.connection lost

**Comment by Andre0512** [comment]
I think I have now finally found the issue :smiley: 
Please checkout the latest beta

**Comment by andremain** [comment]
That was it! It works :)  Thank you so much.
Mind me asking what the issue was?

**Comment by Andre0512** [comment]
Nice, thanks for testing! 🙂 
I found a few bugs, there are two numbers for auto mode internally at hOn (4 and 5) and so far only the 4 has been taken, but your ac and almost all others only support the 5. Also I discovered that not every hvac mode supports every fan mode (e.g. fan only has no auto mode) and then there was a problem switching the mode back to others in certain programs (but that could be a result of the first fix).
